server:
  host: https://localhost
  port: 443
 # port : 8443
  certPath : /home/vjo/projets/rex/rex-ia/testdata/x509/mtls_certs

database:
  host: localhost
  port: 5432
  user: postgres
  password: root
  name: db_rex  

  

  