server:
  host: https://localhost
  port: 3344
  certPath : /home/vjo/projets/rex/rex-ia/testdata/x509

database:
  host: localhost
  port: 5432
  user: postgres
  password: root
  name: db_rex  

  

  