server:
  host: https://159.31.247.10
  port: 443
  certPath : /home/vjo/projets/rex/rex-ia/testdata/x509/mtls_certs

database:
  host: localhost
  port: 5432
  user: postgres
  password: root
  name: db_rex  

pullIntervalMinutes: 360  # 6 hours

  

  